
/*Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose 
values do not exceed four million, find the sum of 
the even-valued terms.
 * 
 */

public class Question2 {

	public static void main(String[] args) {

		int result = evenFibonacci(4000000);
		System.out.println("Result : " + result);
	}

	public static int evenFibonacci(int max) {

		int sum = 0;
		int first = 0;
		int second = 1;
		int temp = first + second;
		while (temp < max) {
			temp = first + second;
			if (temp % 2 == 0) {
				sum += temp;
			}
			first = second;
			second = temp;
		}
		return sum;
	}
}
